from fastapi.middleware.cors import CORSMiddleware

from app.providers.database import db, redis_client
from config.config import settings
from casdoor import CasdoorSDK


def register(app):
    app.debug = settings.DEBUG
    app.title = settings.NAME

    add_global_middleware(app)
    CASDOOR_SDK = CasdoorSDK(
        endpoint=settings.AUTH_ENDPOINT,
        client_id=settings.AUTH_CLIENTID,
        client_secret=settings.AUTH_CLIENTSECRET,
        certificate=settings.AUTH_CERT,
        org_name=settings.ORGNAME,
        application_name=settings.APPNAME,
    )
    app.state.CASDOOR_SDK = CASDOOR_SDK

    # This hook ensures that a connection is opened to handle any queries
    # generated by the request.
    # @app.on_event("startup")
    # def startup():
    #     db.connect()

    # This hook ensures that the connection is closed when we've finished
    # processing the request.

    @app.on_event("shutdown")
    def shutdown():
        if not db.is_closed():
            db.close()

        if redis_client:
            redis_client.close()


def add_global_middleware(app):
    """
    注册全局中间件
    """
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[settings.UI_URL, 'http://localhost:3000', settings.SLURM_API],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )
